### ISSUE TITLE
PRCS-1076 invalid single client access name.

### ISSUE THREAD

**Issue by oracledbashop** [brokedba/vagrant#2]
Hi,

I am getting following error while setting up node1.

PRCS-1076 invalid single client access name. The subnet 198.105.254.0 of scan VIP 198.105.254.23 difference from the subnet 198.105.244.0 of network 1

Regards,
Sudhakar
![error](https://user-images.githubusercontent.com/66651386/106430388-55c3c300-6431-11eb-9496-dcce210aae79.PNG)

**Comment by brokedba** [comment]
Hi @oracledbashop,
You didn't specify any information related to the build you used.  Even for Rac19c there are 3 builds available in the repository.
It's hard to guess from a screen shot. The build and the OS were run the vagrant up from is as important.
  
Could you share below files besides the exact rac build you used ?   
- /config/install.env 
- /config/vagrant.yml

**Comment by oracledbashop** [comment]
Hi, 

Thank for the reply. I was using https://github.com/KoussHD/vagrant.git build and had problem. 

After little research I found another build https://github.com/oracle/vagrant-projects.git and it worked perfectly and was able to install 2 node RAC. I am actively using newly configured 2 node RAC.

I am good now. Please close the ticket.

Thank you for the reply!

Regards,
Sudhakar

**Comment by brokedba** [comment]
Dear @oracledbashop  ,
Glad you got it to work.
However, my builds always worked for me (in windows) and I am available to troubleshoot if needed as all OL8/RHEL8/CENTOS were adapted by me . All other OL7 builds are working perfectly as well and have been forked verbatim from @oraclebase's project.
Now,  I can only do so much if you  don't provide the configuration files I mentioned earlier ;) .

Cheers 
Brokedka

**Comment by brokedba** [comment]
closing the issue.

**Comment by oracledbashop** [comment]
Hi,

Thank you for your email!

I deleted whole build, I will re-clone and will try to replicate the issue.
Will provide all requested files once set up completed at my end.

Thank you again for the reply.

Regards,
Sudhakar

**Comment by oracledbashop** [comment]
Hi,

Here are the details

Build used - https://github.com/KoussHD/vagrant.git

Sending installation log, install.env and vagrant.YML files. 



[config_files.zip](https://github.com/brokedba/vagrant/files/5969295/config_files.zip)

Regards,
Sudhakar

**Comment by brokedba** [comment]
Hi Sudhakar ,
on your first message the error would suggest that  the defined PUBLIC_SUBNET was not matching  SCAN IPs  (192.105.244.x vs 192.105.254.x ) but when I see your install.env It's the default subnet and SCAN IPS that's shown  (which doesn't make sense  , maybe it's not the install.env  you really used ).

Another thing I noticed in your vagrant.yml is that you've chosen 4GB memory for both RAC nodes 
```
node1:
  vm_name: london_rac1
  mem_size: 4096 <===
  cpus: 2
  public_ip: 192.168.78.51
  private_ip: 172.16.100.51
  u01_disk: ./ol8_19_rac1_u01.vdi

node2:
  vm_name: london_rac2
  mem_size: 4096 <===
  cpus: 2
  public_ip: 192.168.78.52
  private_ip: 172.16.100.52
  u01_disk: ./ol8_19_rac2_u01.vdi
``` 
- It's already barely possible to run RAC 12.1 with 4G of RAM let alone a RAC 19c, that'd be delusional.
As described by Tim Hall in the original build
The smallest system you can complete this consumes 16G RAM, with the VM memory settings as follows and nothing else running.
```
dns:
  mem_size: 1024

node1:
  mem_size: 7168

node2:
  mem_size: 6144 
  ```
  
  That is exactly what I am still running on my laptop 
- *NODE2*
![image](https://user-images.githubusercontent.com/29458929/107734675-fdf84800-6ccb-11eb-898b-8db711e12c3d.png)

- *NODE1* 
  
![image](https://user-images.githubusercontent.com/29458929/107734714-0e102780-6ccc-11eb-9459-d54781d32d6c.png)

  I strongly suggest to adjust the memory to the recommended values and do another vagrant up first before troubleshooting the error you're having now.
  
  hope that helps
  cheers 
  @brokedba

**Comment by oracledbashop** [comment]
Hi,

Agreed. But I don’t have enough memory on my laptop, but still it works
well with changed 1GB, 4GB and 4GB. Can we work on latest errors please?

Regards,
Sudhakar
